version: "3.9"
services:
  web:
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app  
    image: node:14
    command: npm start
    ports:
      - "5000:3000"
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"